// <auto-generated />
using Crud.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crud.Domain.Migrations
{
    [DbContext(typeof(CrudContext))]
    partial class CrudContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Crud.Domain.VisitaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Celular")
                        .HasColumnType("bigint");

                    b.Property<string>("Comentario")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(true);

                    b.Property<int>("Motivo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Visita","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = 3163534451L,
                            Correo = "cristiancamilo10_95@outlook.com",
                            Motivo = 2,
                            Nombre = "Cristian Bonilla"
                        },
                        new
                        {
                            Id = 2,
                            Celular = 3201198827L,
                            Comentario = "Productos exclusivos de fragancia VIP Carolina Herrera",
                            Correo = "jessea_19av@gmail.com",
                            Motivo = 1,
                            Nombre = "Jessica Gutierrez"
                        },
                        new
                        {
                            Id = 3,
                            Celular = 3192550012L,
                            Correo = "luz.andre881@gmail.com",
                            Motivo = 3,
                            Nombre = "Luz Andrea Ramos"
                        },
                        new
                        {
                            Id = 4,
                            Celular = 3227179901L,
                            Correo = "sandrylozano89@hotmail.com",
                            Motivo = 1,
                            Nombre = "Sandra Lozano"
                        },
                        new
                        {
                            Id = 5,
                            Celular = 31477810911L,
                            Comentario = "Ropa de gran calidad y al mejor costo",
                            Correo = "santi87.giraldo@gmail.com",
                            Motivo = 2,
                            Nombre = "Felipe Santiago Giraldo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
